---
name: Run Super-Linter

# in quotes to avoid YAMLLint thinking it's a boolean
"on": push

jobs:
  super-linter:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Lint Code Base
        uses: super-linter/super-linter@v5
        env:
          VALIDATE_ALL_CODEBASE: false
          DEFAULT_BRANCH: main
          PYTHON_PYLINT_CONFIG_FILE: .pylintrc
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
